services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course_assistant
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  postgres_data:
